export {default as About} from "./About"
export {default as Education} from "./Education"
export {default as WorkExperience} from "./WorkExperience"
export {default as Projects} from "./Projects"
export {default as Section} from "./Section"
export {default as Footer} from "./Footer"
export {default as SpiderWebBackground} from "./SpiderWebBackground"
export {default as Skills} from "./Skills"